### ISSUE TITLE
.net installation step is unclear

### ISSUE THREAD

**Issue by bill876** [Museus/TunicSaveManager#7]
> When you first try to run the SaveManager, your PC wil prompt you to install .NET, if necessary.

It did, but clicking "yes" to download did not do anything.
Also I did have the supported runtimes of .NET (v6 and v7) installed already.

Looking at the accompanying configs I figured that the required version is `.NET Core 3.1`, and after going to https://dotnet.microsoft.com/en-us/download/dotnet/3.1 and installing the .NET Desktop Runtime 3.1.xx, the app started.

Would be nice to add this to instructions, so other new users will have an easier time
(if it even affects more than just me)

**Comment by Museus** [comment]
Good idea. I'm planning to release a new version targeting .NET 6.0 at some point, but this is definitely worth adding in the mean time. Thank you!
